// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://placeholder.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'placeholder-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a more robust mock client if environment variables are not set
const createMockClient = () => {
  const mockDeduction: any = {
    eq: () => mockDeduction,
    select: () => mockDeduction,
    order: () => mockDeduction,
    limit: () => mockDeduction,
    single: () => mockDeduction,
    insert: () => mockDeduction,
    update: () => mockDeduction,
    delete: () => mockDeduction,
    or: () => mockDeduction,
    match: () => mockDeduction,
    in: () => mockDeduction,
    contains: () => mockDeduction,
    range: () => mockDeduction,
    then: (resolve: any) => resolve({ data: [], error: null }),
    catch: (reject: any) => {
      if (typeof reject === 'function') return reject(new Error('Supabase not configured'));
      return mockDeduction;
    },
  };

  return {
    auth: {
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => { } } } }),
      getSession: () => Promise.resolve({ data: { session: null }, error: null }),
      signInWithPassword: () => Promise.resolve({ data: { user: null, session: null }, error: new Error('Supabase not configured') }),
      signUp: () => Promise.resolve({ data: { user: null, session: null }, error: new Error('Supabase not configured') }),
      signOut: () => Promise.resolve({ error: null }),
      getUser: () => Promise.resolve({ data: { user: null }, error: null }),
    },
    from: () => mockDeduction,
    channel: () => ({
      on: () => ({
        subscribe: () => ({
          unsubscribe: () => { }
        })
      }),
      subscribe: () => ({
        unsubscribe: () => { }
      })
    }),
    storage: {
      from: () => ({
        upload: () => Promise.resolve({ data: null, error: new Error('Supabase not configured') }),
        getPublicUrl: () => ({ data: { publicUrl: '' } }),
        remove: () => Promise.resolve({ data: null, error: new Error('Supabase not configured') })
      })
    }
  };
};

const isConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY && SUPABASE_URL !== 'https://placeholder.supabase.co');

if (!isConfigured) {
  console.warn("⚠️ SUPABASE NOT CONFIGURED: Using mock client. Backend features like Login and Notifications won't work until you set your environment variables on Netlify.");
}

let client;
try {
  client = isConfigured
    ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
    : createMockClient();
} catch (error) {
  console.error('Supabase init failed:', error);
  client = createMockClient();
}

export const supabase = client as any;